set test "kallsyms"

if {![installtest_p]} {untested $test; return}

set script {"probe timer.profile {print_stack(backtrace()); exit()}"}
set passed 0

# don't let stap find kernel debuginfo!
eval spawn env SYSTEMTAP_DEBUGINFO_PATH=$srcdir DEBUGINFOD_URLS= DEBUGINFOD_CACHE_PATH=/dev/null stap --all-modules -e $script
expect {
  -timeout 30
  -re "\\\[kernel\\\]" {
    set passed 1
  }
}
catch { close }; catch { wait }

if {$passed == 1} {
  pass $test
} else {
  fail $test
}
